name: Auto Deploy Test to AWS Lambda

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  deploy:
    name: Auto Test Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install serverless -g
          npm install

      - name: Install serverless-offline
        run: |
          sls plugin install -n serverless-offline

      - name: Deploy to Lambda Test
        run: sls deploy --stage pr$(jq --raw-output .number "$GITHUB_EVENT_PATH")
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
